'use strict';
const fs = require('node:fs');
const cp = require('node:child_process');
const path = require('node:path');
const root = path.resolve(__dirname, '..'), plugin = path.join(root, 'plugin');
const m = JSON.parse(fs.readFileSync(path.join(plugin,'manifest.json')));
if(m.manifestVersion!==5 || Array.isArray(m.host) || m.host.app!=='PS' || m.host.data.apiVersion!==2) throw Error('Invalid distribution manifest');
const distribution=JSON.parse(fs.readFileSync(path.join(plugin,'distribution.json')));
if(distribution.channel!=='independent'||m.id!=='com.josueeguia.halftonedtf')throw Error('Source distribution identity changed');
if(JSON.parse(fs.readFileSync(path.join(root,'package.json'))).version!==m.version)throw Error('Package and plugin versions differ');
for(const file of fs.readdirSync(plugin).filter(name=>name.endsWith('.js'))) cp.execFileSync(process.execPath,['--check',path.join(plugin,file)]);
const html=fs.readFileSync(path.join(plugin,'index.html'),'utf8'), js=fs.readFileSync(path.join(plugin,'main.js'),'utf8');
for(const match of js.matchAll(/\$\('([^']+)'\)/g)) if(!html.includes(`id="${match[1]}"`)) throw Error('Missing control '+match[1]);
const ids=[...html.matchAll(/id="([^"]+)"/g)].map(m=>m[1]);if(new Set(ids).size!==ids.length)throw Error('Duplicate HTML IDs');
console.log('Manifest, syntax and control references OK. Photoshop execution remains a manual check.');
