"""Stage sources for Adobe UDT; validate a human-packaged installer before release.

This script never calls a generated ZIP an official Adobe package.
"""
import argparse
import hashlib
import json
import re
import shutil
import subprocess
from pathlib import Path
from urllib.parse import urlparse
from zipfile import ZipFile

ROOT = Path(__file__).resolve().parents[1]


def stage(channel, marketplace_id=None, marketplace_url=None):
    source = ROOT / 'plugin'
    manifest = json.loads((source / 'manifest.json').read_text())
    if channel == 'marketplace':
        if not marketplace_id or not re.fullmatch(r'[A-Za-z0-9_.-]+', marketplace_id) or marketplace_id == manifest['id']:
            raise ValueError('Use the distinct plugin ID generated by Adobe Developer Distribution.')
        url = urlparse(marketplace_url or '')
        if url.scheme != 'https' or url.netloc != 'exchange.adobe.com' or url.query or url.fragment:
            raise ValueError('Provide the actual HTTPS Marketplace listing URL from Adobe.')
    target = ROOT / 'dist' / ('adobe-' + channel)
    if target.exists():
        shutil.rmtree(target)
    shutil.copytree(source, target)
    if channel == 'marketplace':
        manifest['id'] = marketplace_id
        # Marketplace edition uses Adobe distribution, not the independent updater.
        manifest['requiredPermissions'].pop('network', None)
    (target / 'manifest.json').write_text(json.dumps(manifest, indent=2) + '\n')
    (target / 'distribution.json').write_text(json.dumps({'channel': channel, 'marketplaceUrl': marketplace_url if channel == 'marketplace' else None}, indent=2) + '\n')
    return target


def validate_ccx(file):
    file = Path(file)
    manifest = json.loads((ROOT / 'plugin/manifest.json').read_text())
    if file.name != f"Halftone-DTF-{manifest['version']}.ccx" or not 0 < file.stat().st_size <= 50 * 1024 * 1024:
        raise ValueError('Wrong installer filename or size.')
    with ZipFile(file) as archive:
        names = archive.namelist()
        if len(names) != len(set(names)) or archive.testzip() is not None:
            raise ValueError('Invalid CCX archive.')
        expected = {p.relative_to(ROOT / 'plugin').as_posix(): p for p in (ROOT / 'plugin').rglob('*') if p.is_file()}
        for name, source in expected.items():
            if name not in names or archive.read(name) != source.read_bytes():
                raise ValueError('Official installer does not match this commit: ' + name)
        for name in names:
            if name.endswith('/'):
                continue
            if name not in expected:
                raise ValueError('Unexpected file in installer: ' + name)
    return manifest


def release(file, output):
    subprocess.run(['node', str(ROOT / 'scripts/check-release.js')], cwd=ROOT, check=True)
    manifest = validate_ccx(file)
    data = {
        'schema': 'halftone-update-v1', 'channel': 'independent',
        'pluginId': manifest['id'], 'version': manifest['version'],
        'minPhotoshop': manifest['host']['minVersion'],
        'packaging': 'adobe-udt', 'nativeValidated': True,
        'ccx': {'name': Path(file).name, 'sha256': hashlib.sha256(Path(file).read_bytes()).hexdigest(), 'size': Path(file).stat().st_size}
    }
    output = Path(output)
    output.parent.mkdir(parents=True, exist_ok=True)
    output.write_text(json.dumps(data, indent=2) + '\n')
    return output


if __name__ == '__main__':
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument('--channel', choices=['independent', 'marketplace'], default='independent')
    parser.add_argument('--marketplace-id')
    parser.add_argument('--marketplace-url')
    parser.add_argument('--official-ccx', type=Path)
    parser.add_argument('--output', type=Path, default=ROOT / 'dist/halftone-update.json')
    args = parser.parse_args()
    print(release(args.official_ccx, args.output) if args.official_ccx else stage(args.channel, args.marketplace_id, args.marketplace_url))
